cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'git'
# brew 'go'
brew 'grc'
tap 'heroku/brew'
brew 'heroku'
brew 'openssl'
# brew 'node'
brew 'readline'
# brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
# brew 'spark'
brew 'wget'
# brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

tap 'homebrew/cask'
cask '1password'
cask '1password-cli'
cask 'alfred'
cask 'atom'
cask 'cyberduck'
cask 'discord'
cask 'dropbox'
cask 'epichrome'
cask 'firefox'
cask 'fluid'
cask 'gimp'
cask 'google-chrome'
cask 'insomnia'
cask 'iterm2'
cask 'pycharm'
cask 'rubymine'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'sublime-text'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'virtualbox'
# cask 'vlc'
cask 'wavebox'
